_core:
  default_config_hash: 8GyocqC2nyRrMjMdTwkLg8XLON-hZQ68wsuOEjxmCx0
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: /TechDrupalers/web/themes/contrib/bootstrap/favicon.ico
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
third_party_settings:
  shortcut:
    module_link: true
schemas:
  bootstrap: 8000
  breeze: 8000
