_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  advanced_cors: 0
  asset_injector: 0
  automated_cron: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  commerce: 0
  commerce_api: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_invoice: 0
  commerce_log: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_payment_example: 0
  commerce_price: 0
  commerce_product: 0
  commerce_promotion: 0
  commerce_store: 0
  commerce_tax: 0
  commerce_wishlist: 0
  config: 0
  contact: 0
  contextual: 0
  cors_ui: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_print: 0
  entity_print_views: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  jsonapi: 0
  jsonapi_defaults: 0
  jsonapi_extras: 0
  jsonapi_hypermedia: 0
  jsonapi_resources: 0
  layout_builder: 0
  layout_builder_styles: 0
  layout_discovery: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  profile: 0
  rest: 0
  rest_api_authentication: 0
  rest_export: 0
  restui: 0
  search: 0
  serialization: 0
  shortcut: 0
  state_machine: 0
  structure_sync: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_entity_form_field: 0
  views_ui: 0
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  bartik: 0
  seven: 0
  gin: 0
  bootstrap: 0
  breeze: 0
  stable9: 0
  tara: 0
  stable: 0
  classy: 0
  newsplus_lite: 0
  magazine_lite: 0
profile: standard
