_core:
  default_config_hash: lhknqI_UWOrAbQH9SLBSF7MVG-hc49r4GShA8pFG4gY
scope_provider: dynamic
token_cron_batch_size: 0
disable_openid_connect: false
access_token_expiration: 300
authorization_code_expiration: 300
refresh_token_expiration: 1209600
remember_clients: true
use_implicit: false
