_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 5cf8e3ff-a593-45da-8947-b52b0269676f
name: 'Export Portal'
mail: exportportal@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/10
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
